/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkExporterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultExportDir: "output",
  defaultMaxDepth: 2,
  exportOutsideVault: false
};
var LinkExporterPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("folder-output", "Export linked files", () => {
      this.openExportModal();
    });
    this.addCommand({
      id: "export-linked-files",
      name: "Export linked files",
      callback: () => {
        this.openExportModal();
      }
    });
    this.addSettingTab(new LinkExporterSettingTab(this.app, this));
  }
  openExportModal() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian.Notice("\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u5143\u306E\u30D5\u30A1\u30A4\u30EB\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    new ExportModal(this.app, this, activeFile).open();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ExportModal = class extends import_obsidian.Modal {
  constructor(app, plugin, sourceFile) {
    super(app);
    this.plugin = plugin;
    this.sourceFile = sourceFile;
    this.maxDepth = plugin.settings.defaultMaxDepth;
    this.exportDir = plugin.settings.defaultExportDir;
    this.exportOutsideVault = plugin.settings.exportOutsideVault;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("link-exporter-modal");
    contentEl.createEl("h2", { text: "Export Linked Files" });
    contentEl.createEl("p", {
      text: `\u30BD\u30FC\u30B9: ${this.sourceFile.basename}`,
      cls: "link-exporter-source"
    });
    const depthSetting = new import_obsidian.Setting(contentEl).setName("\u63A2\u7D22\u968E\u5C64").setDesc("0 = \u3053\u306E\u30D5\u30A1\u30A4\u30EB\u306E\u307F\u30011 = \u76F4\u63A5\u30EA\u30F3\u30AF\u5148\u30012+ = \u30EA\u30F3\u30AF\u5148\u306E\u30EA\u30F3\u30AF\u5148...");
    const depthValueEl = depthSetting.controlEl.createEl("span", {
      text: String(this.maxDepth),
      cls: "link-exporter-depth-value"
    });
    depthSetting.addSlider(
      (slider) => slider.setLimits(0, 10, 1).setValue(this.maxDepth).setDynamicTooltip().onChange((value) => {
        this.maxDepth = value;
        depthValueEl.setText(String(value));
      })
    );
    const exportModeToggle = new import_obsidian.Setting(contentEl).setName("\u4FDD\u7BA1\u5EAB\u5916\u306B\u4FDD\u5B58").setDesc("ON\u306B\u3059\u308B\u3068\u3001\u30C7\u30B9\u30AF\u30C8\u30C3\u30D7\u3084Documents\u306A\u3069\u4FDD\u7BA1\u5EAB\u5916\u306E\u30D5\u30A9\u30EB\u30C0\u3092\u9078\u629E\u3067\u304D\u307E\u3059");
    exportModeToggle.addToggle(
      (toggle) => toggle.setValue(this.exportOutsideVault).onChange((value) => {
        this.exportOutsideVault = value;
        this.renderExportDirSetting(exportDirContainer);
      })
    );
    const exportDirContainer = contentEl.createDiv("link-exporter-dir-container");
    this.renderExportDirSetting(exportDirContainer);
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8").setCta().onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("\u51E6\u7406\u4E2D...");
        await this.runExport();
        btn.setDisabled(false);
        btn.setButtonText("\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8");
      })
    );
    this.statusEl = contentEl.createEl("div", {
      cls: "link-exporter-status",
      text: "\u5F85\u6A5F\u4E2D"
    });
  }
  renderExportDirSetting(container) {
    container.empty();
    if (this.exportOutsideVault) {
      const pathDisplay = container.createEl("div", { cls: "link-exporter-path-display" });
      pathDisplay.setText(this.exportDir || "\u672A\u9078\u629E");
      const browseBtn = container.createEl("button", {
        text: "\u30D5\u30A9\u30EB\u30C0\u3092\u9078\u629E...",
        cls: "link-exporter-browse-btn"
      });
      browseBtn.addEventListener("click", async () => {
        try {
          const electron = window.require("electron");
          const result = await electron.remote.dialog.showOpenDialog({
            properties: ["openDirectory", "createDirectory"],
            title: "\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u5148\u30D5\u30A9\u30EB\u30C0\u3092\u9078\u629E"
          });
          if (!result.canceled && result.filePaths.length > 0) {
            this.exportDir = result.filePaths[0];
            pathDisplay.setText(this.exportDir);
          }
        } catch (e) {
          new import_obsidian.Notice("\u30D5\u30A9\u30EB\u30C0\u9078\u629E\u30C0\u30A4\u30A2\u30ED\u30B0\u3092\u958B\u3051\u307E\u305B\u3093\u3067\u3057\u305F\u3002");
          console.error("Link Exporter: Failed to open folder dialog", e);
        }
      });
    } else {
      new import_obsidian.Setting(container).setName("\u4FDD\u5B58\u5148\u30D5\u30A9\u30EB\u30C0").setDesc("\u4FDD\u7BA1\u5EAB\u5185\u306E\u30D5\u30A9\u30EB\u30C0\u30D1\u30B9").addText(
        (text) => text.setPlaceholder("output").setValue(this.exportDir).onChange((value) => {
          this.exportDir = value;
        })
      );
    }
  }
  async runExport() {
    const processedPaths = /* @__PURE__ */ new Set();
    let count = 0;
    const updateStatus = (msg) => {
      this.statusEl.setText(msg);
    };
    if (this.exportOutsideVault) {
      const fs = window.require("fs");
      const path = window.require("path");
      const exportPath = this.exportDir;
      if (!fs.existsSync(exportPath)) {
        fs.mkdirSync(exportPath, { recursive: true });
      }
      const exportRecursive = async (file, depth) => {
        if (!file || file.extension !== "md" || depth > this.maxDepth || processedPaths.has(file.path)) {
          return;
        }
        processedPaths.add(file.path);
        const content = await this.app.vault.read(file);
        const destPath = path.join(exportPath, file.name);
        fs.writeFileSync(destPath, content, "utf-8");
        count++;
        updateStatus(`\u51E6\u7406\u4E2D... ${count} \u30D5\u30A1\u30A4\u30EB`);
        const metadata = this.app.metadataCache.getFileCache(file);
        const links = (metadata == null ? void 0 : metadata.links) || [];
        for (const link of links) {
          const targetFile = this.app.metadataCache.getFirstLinkpathDest(link.link, file.path);
          if (targetFile && targetFile instanceof import_obsidian.TFile) {
            await exportRecursive(targetFile, depth + 1);
          }
        }
      };
      await exportRecursive(this.sourceFile, 0);
      updateStatus(`\u5B8C\u4E86: ${count} \u30D5\u30A1\u30A4\u30EB\u3092 ${exportPath} \u306B\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u3057\u307E\u3057\u305F`);
      new import_obsidian.Notice(`${count} \u500B\u306E\u30D5\u30A1\u30A4\u30EB\u3092 ${exportPath} \u306B\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u3057\u307E\u3057\u305F`);
    } else {
      const exportDirName = this.exportDir || "output";
      const exportFolder = this.app.vault.getAbstractFileByPath(exportDirName);
      if (!exportFolder) {
        await this.app.vault.createFolder(exportDirName);
      }
      const exportRecursive = async (file, depth) => {
        if (!file || file.extension !== "md" || depth > this.maxDepth || processedPaths.has(file.path)) {
          return;
        }
        processedPaths.add(file.path);
        const content = await this.app.vault.read(file);
        const destPath = `${exportDirName}/${file.name}`;
        const existingFile = this.app.vault.getAbstractFileByPath(destPath);
        if (!existingFile) {
          await this.app.vault.create(destPath, content);
        } else if (existingFile instanceof import_obsidian.TFile) {
          await this.app.vault.modify(existingFile, content);
        }
        count++;
        updateStatus(`\u51E6\u7406\u4E2D... ${count} \u30D5\u30A1\u30A4\u30EB`);
        const metadata = this.app.metadataCache.getFileCache(file);
        const links = (metadata == null ? void 0 : metadata.links) || [];
        for (const link of links) {
          const targetFile = this.app.metadataCache.getFirstLinkpathDest(link.link, file.path);
          if (targetFile && targetFile instanceof import_obsidian.TFile) {
            await exportRecursive(targetFile, depth + 1);
          }
        }
      };
      await exportRecursive(this.sourceFile, 0);
      updateStatus(`\u5B8C\u4E86: ${count} \u30D5\u30A1\u30A4\u30EB\u3092 ${exportDirName} \u306B\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u3057\u307E\u3057\u305F`);
      new import_obsidian.Notice(`${count} \u500B\u306E\u30D5\u30A1\u30A4\u30EB\u3092 ${exportDirName} \u306B\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u3057\u307E\u3057\u305F`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var LinkExporterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Link Exporter \u8A2D\u5B9A" });
    new import_obsidian.Setting(containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u4FDD\u5B58\u5148\u30D5\u30A9\u30EB\u30C0").setDesc("\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u5148\u306E\u30C7\u30D5\u30A9\u30EB\u30C8\u30D1\u30B9").addText(
      (text) => text.setPlaceholder("output").setValue(this.plugin.settings.defaultExportDir).onChange(async (value) => {
        this.plugin.settings.defaultExportDir = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u30C7\u30D5\u30A9\u30EB\u30C8\u63A2\u7D22\u968E\u5C64").setDesc("\u30EA\u30F3\u30AF\u3092\u8FBF\u308B\u968E\u5C64\u6570\u306E\u30C7\u30D5\u30A9\u30EB\u30C8\u5024\uFF080\u301C10\uFF09").addSlider(
      (slider) => slider.setLimits(0, 10, 1).setValue(this.plugin.settings.defaultMaxDepth).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.defaultMaxDepth = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u4FDD\u7BA1\u5EAB\u5916\u306B\u4FDD\u5B58\uFF08\u30C7\u30D5\u30A9\u30EB\u30C8\uFF09").setDesc("ON\u306B\u3059\u308B\u3068\u3001\u30E2\u30FC\u30C0\u30EB\u306E\u30C7\u30D5\u30A9\u30EB\u30C8\u304C\u4FDD\u7BA1\u5EAB\u5916\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u306B\u306A\u308A\u307E\u3059").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.exportOutsideVault).onChange(async (value) => {
        this.plugin.settings.exportOutsideVault = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
